language: python
python:
  - "3.7.3"

stages:
  - name: test
  - name: deploy

jobs:
  include:
    - stage: test
      name: Unit Tests
      script: python manage.py test
    - stage: deploy
      name: Heroku Deploy
      script: /bin/true
      deploy:
        provider: heroku
        api_key:
          secure: fp22JgJaWyC5MlvdVPjvHnltRSHmSi9wfb8VMpwHthnWEZrmXhYTgwxbdb8oCHCv8f0Afh5rPFsAm3JyKK1CziMGVfkh/aTqPsXTXSj/ca8tYpaVGofiwfceKysEjoO4JGUJK+pRVuLMD13D0035YdHkX3y7mo6d8FCsA1YzBtL32xsqbasf6bzQHOasPtKh1VaLbP8XqBlH3aLaoZrVAThjrWN1Pl/GW745/tV7I8mY9DjaXNjUFIeH+M5b2H2UxE0oMXNW8W6vgJwveejGH8HPo1oZjhjDFtLcohQk0jU0zXenKL+Tr8nV+D6VwZHMfkmZNW8LVWIPPYRZYEenH9jnKACduGFsGz8tv+vYgM12z5bfr442dY97M1EOPUFqL7nCi8AJ3czFIIo0y4OdLPdJJbS6BNdoMF8fTozD4+6Xm8EM9KEvg5P4aTm+7AhyHuMwnh2GDgv2giX8kGM+yUwLWETHA1Yxoukix8XdRI/bL8q5WYtn1qVKdkRbSNYgVxJJVyuj5pO/fu+tu8sqXYhjrLpNizCrKq1Aui4+bdFax+dN3JHmB51iyf8AQ3nYcnuxxW47VY37zZn3YZ57BBltMQSom71ran5SGWgudbhlxu30xmnjx7gXAz/kZVK+QA5h9j0GQkjCuTDykqybM8m/h/7SNfHxkLUpQjp+hWA=
        app: lhcs-acelera-ecomm
        on: master
        run: "python manage.py migrate"
